Feature: Preload bulk epubs with preset lcp passphrase
ekitabu-LLC/ekitabu-readium-desktop-working pull request #48
Opened 2020-11-27 17:33 UTC by aferditamuriqi

2020-11-30 19:24 UTC, mutterback commented
@kevinmainairungu could you run this build for review when you're back this week?

2020-12-07 14:43 UTC, kevinmainairungu commented
@mutterback Adding these steps to reproduce:

- when the app starts and Preloaded section is empty, you will see a plus button
- using the Plus button you can select a directory to be preloaded
- in that directory you need to have a file that has the extension .passphrase, in there you add the hashed passphrase that these books work with (only the hash, nothing else) (actually this file can also be just named .passhprase without any prefix, which will still be readable but invisible for the user when they look into the directory)
- if that file doesn’t exist, no preload
- in that directory you place all your epubs, .epub extension is needed
- once you preload successfully, the preload Plus button disappears
- you can see in the video i added a tiny easter egg to be able to delete all preloaded files, the very end corner is clickable
- once you delete all the preload is active again.

2020-12-18 11:02 UTC, kevinmainairungu commented on src/main/redux/sagas/api/publication/preload/preload.ts
> +export async function preload(filePathArray: string | string[], passphrase: string): Promise<PublicationView[]> {
The preload function takes in the filepath for the sample epubs and the passprase

2020-12-18 11:07 UTC, kevinmainairungu commented on src/common/api/interface/preload.interface.ts
> +export interface IPreloadApi {
preload tag `is done` when a preload is complete

2020-12-18 11:16 UTC, kevinmainairungu reviewed
@aferditamuriqi took my time to review the code even though it's assigned to Brett. Leaving a  comment.

2020-12-18 11:16 UTC, kevinmainairungu commented
@mutterback @aferditamuriqi apologies for taking too much time on this.I tested this out with the sample epubs. I got the expected output.

2021-01-04 09:33 UTC, kevinmainairungu approved these changes
Used the steps recommended by @aferditamuriqi to check the preload feature. Also took some time to understand what file encryption process and the files required for the pre-load to be successful.

2021-01-04 18:43 UTC, brettins requested changes

2021-01-04 18:43 UTC, brettins commented on src/main/redux/sagas/api/publication/index.ts
> +import { preload} from "./preload/preload";
missing a space after "preload"

2021-01-04 18:43 UTC, brettins commented on src/main/api/preload.ts
> +import {inject, injectable} from "inversify";
The rest of the app uses `{ name }`  as opposed to `{name}` format for imports, if possible we should stick to the same convention

2021-01-04 18:43 UTC, brettins commented on src/renderer/common/components/dialog/publicationInfos/publicationInfoContent.tsx
> +import {PublicationView} from "readium-desktop/common/views/publication";
Should be `{ PublicationView }`

2021-01-04 18:43 UTC, brettins commented on src/renderer/library/components/catalog/PreloadSearchForm.tsx
> +        // this.inputRef.current.select();
Do we need this for the future? Or can it be deleted?

2021-01-04 18:43 UTC, brettins commented on src/renderer/library/components/catalog/PreloadSearchForm.tsx
> +            const target = "/preloaded/search/text/" + value; // + this.props.location.search;
Will we need the code in the trailing comments here later?

2021-01-04 18:43 UTC, brettins commented on src/renderer/library/components/catalog/PublicationPreloadButton.tsx
> +        delay(300);
Where is 300 coming from? Can this not be a promise/an await?

2021-01-04 18:43 UTC, brettins commented on src/renderer/library/components/catalog/PublicationPreloadButton.tsx
> +                // this.preloadDone = localStorage.getItem("preloadDone") === "true";
dead code, please remove

2021-01-04 18:43 UTC, brettins commented on src/renderer/library/components/catalog/PublicationPreloadButton.tsx
> +        // localStorage.setItem("preloadDone", String(bool));
dead code

2021-01-04 18:43 UTC, brettins commented on src/renderer/library/components/dialog/publicationInfos/catalogLcpControls.tsx
> +                            // lsdStatus === StatusEnum.Expired &&
dead code

2021-01-07 18:22 UTC, kevinmainairungu commented
@aferditamuriqi any update from Brett's recommendations?I wanted to create a release that has these changes and also some other changes that Brett has been working on. This release will be tested out next week by the team.

2021-01-22 16:39 UTC, aferditamuriqi commented on src/renderer/library/components/catalog/PreloadSearchForm.tsx
> +        // this.inputRef.current.select();
i'll remove it, but it seems to be in several other areas as well.

2021-01-22 16:40 UTC, aferditamuriqi commented on src/renderer/library/components/catalog/PreloadSearchForm.tsx
> +            const target = "/preloaded/search/text/" + value; // + this.props.location.search;
this is also from original code for search, i'll remove it here, but it might be in original search still.

2021-01-22 16:42 UTC, aferditamuriqi commented on src/renderer/library/components/dialog/publicationInfos/catalogLcpControls.tsx
> +                            // lsdStatus === StatusEnum.Expired &&
this is from original code, but i can remove it

2021-01-22 16:51 UTC, aferditamuriqi commented on src/renderer/library/components/catalog/PublicationPreloadButton.tsx
> +        delay(300);
used the same as in the original delete function, apparently a promise/await doesn't work here.

2021-01-22 17:31 UTC, brettins approved these changes

2021-01-24 16:31 UTC, merged