Update DeviceInfoQr.tsx
ekitabu-LLC/ekitabu-readium-desktop-working pull request #76
Opened 2021-01-26 08:19 UTC by dobbz

Get full info of device specifications in QR code.

2021-01-26 12:14 UTC, kevinmainairungu approved these changes
@mutterback please check this video recording of this code change. This is what we need to fetch from the devices. We might need to edit more so that the .toJson output can be useful when uploading to power apps.

2021-03-25 08:11 UTC, kevinmainairungu commented
@mutterback these are the changes we wanted to be added to the feature/dev branch. It has the correct data we need for collecting device specs. 
@brettins could this changes be merged into feature/dev

2021-03-26 06:12 UTC, brettins requested changes

2021-03-26 06:12 UTC, brettins commented on .vscode/settings.json
> +  "python.pythonPath": "c:\\Python38\\python.exe",
This is windows specific & machine specific and doesn't belong in a commit

2021-03-26 06:12 UTC, brettins commented on src/renderer/library/components/settings/DeviceInfoQr.tsx
> +        windowsSerialNumber: deviceInfo.osInfo,
these variable names are no longer correct if we're getting the entire `osInfo` and `sysInfo`,

2021-03-26 21:10 UTC, brettins commented
@kevinmainairungu all of the translation files have been moved out of "en.md" type files and into `en.xhtml` files in the new version of Readium, so most of these translations won't work anymore.

2021-05-07 14:46 UTC, kevinmainairungu commented on src/renderer/library/components/settings/DeviceInfoQr.tsx
> +        windowsSerialNumber: deviceInfo.osInfo,
Changed variables names

2021-05-07 14:50 UTC, kevinmainairungu commented on .vscode/settings.json
> +  "python.pythonPath": "c:\\Python38\\python.exe",
added to .gitignore.

2021-05-07 15:02 UTC, closed without merging